### ISSUE TITLE
scripts/* and README are out of date and not working

### ISSUE THREAD

**Issue by vorburger** [mojaloop/postman#147]
The `OSS-New-Deployment-FSP-Setup.postman_collection` mentioned on and linked from both https://github.com/mojaloop/postman/blob/master/README.md and https://github.com/mojaloop/postman/blob/master/scripts/setupDockerCompose-HubAccount.sh doesn't seem to exist?

Anymore, likely. I'm guessing it's been renamed to .. which one of these `*Setup*` is the right new one?

* `New-Deployment-FSP_Setup_MojaloopSims.postman_collection.json` (probably, most similar name)
* `ML_OSS_Setup_LegacySim.postman_collection.json` (probably not, seeig "Legacy")
* `MojaloopHub_Setup.postman_collection.json` (what's that?)

**Comment by vorburger** [comment]
Given that [*PayeeFSP.sh](https://github.com/mojaloop/postman/blob/master/scripts/setupDockerCompose-PayeeFSP.sh) uses `--folder='payeefsp (p2p transfers)'` and that is in `ML_OSS_Setup_LegacySim.postman_collection.json`, I've made a start to fix this by raising PR #148 fixing the script to use that.

BTW The scripts were also hard-coded to `environments/Mojaloop-Local-Docker-Compose.postman_environment.json`, I'll make them flexible to take the environment as an argument, so that it's easier to use this with those `*.local` names on a local Kubernetes with an Ingress.

The README should still be updated by someone to clarify which of the Collections is for what.

**Comment by elnyry-sam-k** [comment]
@vorburger , please review the release notes here: https://github.com/mojaloop/helm/releases/tag/v10.4.0; Especially, check out the "Notes on simulators", item#3 in the first section.. hope that helps with the collections at least.. Also, you can still use Legacy collections

**Comment by elnyry-sam-k** [comment]
@vorburger - if this is now resolved, please confirm and we can close this. Thank you!

**Comment by elnyry-sam-k** [comment]
Mojaloop now uses [Testing ToolKit](https://github.com/mojaloop/ml-testing-toolkit) (TTK) for running tests and collections defined in [TTK test-cases](https://github.com/mojaloop/testing-toolkit-test-cases)..
