### ISSUE TITLE
One test of Get Party Receiver fails when running the Golden Path collection

### ISSUE THREAD

**Issue by osparamatrix** [mojaloop/postman#86]
I was tasked to deploy Mojaloop on a google cloud vm, which I finished by 8th Feb 2020. 
I have referred the standard deployment docs of Mojaloop and all the pods seem to be running when viewing through the kubernetes dashboard.
Then I cloned the postman repo of Mojaloop and imported the recommended collections in postman ui.
After that, I ran the postman collections in the following order:-
1. OSS-New-Deployment-FSP-Setup (All tests were successful)
2. Golden_Path(One test failed. Rest were successful)

Only one test of the api i.e. Golden_Path -> p2p_money_transfer ->p2p_happy_path SEND QUOTE -> Get Party Receiver failed.
I have attached the postman runner report(just convert from txt to json as I couldn't upload json file)
[Golden_Path.postman_test_run.txt](https://github.com/mojaloop/postman/files/4196903/Golden_Path.postman_test_run.txt)
) for your reference.
I just need clarification whether:-
1. Are the tests in the collection yet to be updated?
2. Or do I need to deploy a more recent version of Mojaloop?

**Comment by elnyry** [comment]
@osparamatrix - #1: The tests here should be up-to-date.
#2: Possibly

So, which version of Helm are you using to deploy Mojaloop or how are you deploying it if you're using a different method?

We use this on a daily basis and have 100% pass rate (unless there are any timing issues- meaning tests happening in parallel or infra time outs )

**Comment by osparamatrix** [comment]
Helm version 3 is being used. And the only difference I came across during deployment was that the tiller setup was not required. Addition of repo and install steps were the same.

If you might have checked the postman runner report, the test that failed checks a response header "accept" value, which in this case was application/json. But it expected something else. So I asked whether the tests needed any update.

But could you elaborate on point 2 you made. That I would possibly have to deploy a more recent version of Mojaloop. If you could mention the version number, that would be helpful.

**Comment by elnyry** [comment]
@osparamatrix we have a new Helm release that was just released: https://github.com/mojaloop/helm/releases/tag/v8.8.0

I would recommend using this moving forward. We haven't tested things out with Helm3 so there may be issues there, but thats on the list for this Program Increment (we're working on upgrading Node version right now to 12.16.0 LTS).

If you still see any issue with ALS (accept header issue), feel free to log a [bug](https://github.com/mojaloop/project/issues/new?assignees=&labels=bug&template=bug_report.md&title=) or reach out.

**Comment by osparamatrix** [comment]
@elnyry. As per your suggestion, I updated the chart to v8.8.0, installed the release and re-ran the tests again. None failed. Everything worked fine.
Thanks for your help.
